import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import clsx from 'clsx';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Candra Wali S | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'overflow-x-hidden')}>{children}</body>
    </html>
  );
}
